"""add missing indexes

Revision ID: 6cace61fd0c8
Revises: 001
Create Date: 2026-05-22 22:11:51.648867
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6cace61fd0c8'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_departments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('mode_type', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('auto_bind', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('modifier_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_sys_departments_parent_id'), 'sys_departments', ['parent_id'], unique=False)
    op.create_table('sys_dictionary',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_dictionary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_ip_rules',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('rule_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('modifier_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_ip_rules_ip_address'), 'sys_ip_rules', ['ip_address'], unique=False)
    op.create_table('sys_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('ipaddress', sqlmodel.sql.sqltypes.AutoString(length=39), nullable=True),
    sa.Column('browser', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('system', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_result', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('modifier_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_menumeta',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('r_svg_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_show_menu', sa.Integer(), nullable=False),
    sa.Column('is_show_parent', sa.Integer(), nullable=False),
    sa.Column('is_keepalive', sa.Integer(), nullable=False),
    sa.Column('frame_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('frame_loading', sa.Integer(), nullable=False),
    sa.Column('transition_enter', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('transition_leave', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_hidden_tag', sa.Integer(), nullable=False),
    sa.Column('fixed_tag', sa.Integer(), nullable=False),
    sa.Column('dynamic_level', sa.Integer(), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('modifier_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_roles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('modifier_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_sys_roles_name'), 'sys_roles', ['name'], unique=True)
    op.create_table('sys_systemconfig',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('access', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('inherit', sa.Integer(), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('modifier_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('sys_userloginlog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('ipaddress', sqlmodel.sql.sqltypes.AutoString(length=39), nullable=True),
    sa.Column('browser', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('system', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('agent', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('login_type', sa.Integer(), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('modifier_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_menus',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('menu_type', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('component', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('modifier_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('meta_id', sa.String(length=32), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['sys_menumeta.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_menus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meta_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sys_menus_parent_id'), 'sys_menus', ['parent_id'], unique=False)
    op.create_table('sys_users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=6), nullable=True),
    sa.Column('is_superuser', src.infrastructure.database.models.user.IntEnumColumn(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('is_staff', src.infrastructure.database.models.user.IntEnumColumn(), nullable=True),
    sa.Column('is_active', src.infrastructure.database.models.user.IntEnumColumn(), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('mode_type', src.infrastructure.database.models.user.IntEnumColumn(), nullable=True),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('gender', src.infrastructure.database.models.user.IntEnumColumn(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('modifier_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('dept_id', sa.String(length=32), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=6), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['sys_departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_users_dept_id'), 'sys_users', ['dept_id'], unique=False)
    op.create_index(op.f('ix_sys_users_email'), 'sys_users', ['email'], unique=False)
    op.create_index(op.f('ix_sys_users_phone'), 'sys_users', ['phone'], unique=False)
    op.create_index(op.f('ix_sys_users_username'), 'sys_users', ['username'], unique=True)
    op.create_table('sys_userinfo_roles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('userinfo_id', sa.String(length=32), nullable=False),
    sa.Column('userrole_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['userinfo_id'], ['sys_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userrole_id'], ['sys_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_userrole_menu',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('userrole_id', sa.String(length=32), nullable=False),
    sa.Column('menu_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['sys_menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userrole_id'], ['sys_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_userrole_menu')
    op.drop_table('sys_userinfo_roles')
    op.drop_index(op.f('ix_sys_users_username'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_phone'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_email'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_dept_id'), table_name='sys_users')
    op.drop_table('sys_users')
    op.drop_index(op.f('ix_sys_menus_parent_id'), table_name='sys_menus')
    op.drop_table('sys_menus')
    op.drop_table('sys_userloginlog')
    op.drop_table('sys_systemconfig')
    op.drop_index(op.f('ix_sys_roles_name'), table_name='sys_roles')
    op.drop_table('sys_roles')
    op.drop_table('sys_menumeta')
    op.drop_table('sys_logs')
    op.drop_index(op.f('ix_sys_ip_rules_ip_address'), table_name='sys_ip_rules')
    op.drop_table('sys_ip_rules')
    op.drop_table('sys_dictionary')
    op.drop_index(op.f('ix_sys_departments_parent_id'), table_name='sys_departments')
    op.drop_table('sys_departments')
    # ### end Alembic commands ###
