"""add missing indexes

Revision ID: 6cace61fd0c8
Revises: 001
Create Date: 2026-05-22 22:11:51.648867
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6cace61fd0c8'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 第一个迁移(001)已通过 SQLModel.metadata.create_all() 创建了所有表
    # 此迁移仅补充缺失的索引
    # 使用 IF NOT EXISTS 避免重复创建
    from sqlalchemy import inspect
    bind = op.get_bind()
    insp = inspect(bind)

    # 仅创建索引（表已在 001 迁移中创建）
    existing_indexes = {idx['name'] for tbl in insp.get_table_names() for idx in insp.get_indexes(tbl)}

    if 'ix_sys_departments_parent_id' not in existing_indexes:
        op.create_index(op.f('ix_sys_departments_parent_id'), 'sys_departments', ['parent_id'], unique=False)
    if 'ix_sys_ip_rules_ip_address' not in existing_indexes:
        op.create_index(op.f('ix_sys_ip_rules_ip_address'), 'sys_ip_rules', ['ip_address'], unique=False)
    if 'ix_sys_roles_name' not in existing_indexes:
        op.create_index(op.f('ix_sys_roles_name'), 'sys_roles', ['name'], unique=True)
    if 'ix_sys_menus_parent_id' not in existing_indexes:
        op.create_index(op.f('ix_sys_menus_parent_id'), 'sys_menus', ['parent_id'], unique=False)
    if 'ix_sys_users_dept_id' not in existing_indexes:
        op.create_index(op.f('ix_sys_users_dept_id'), 'sys_users', ['dept_id'], unique=False)
    if 'ix_sys_users_email' not in existing_indexes:
        op.create_index(op.f('ix_sys_users_email'), 'sys_users', ['email'], unique=False)
    if 'ix_sys_users_phone' not in existing_indexes:
        op.create_index(op.f('ix_sys_users_phone'), 'sys_users', ['phone'], unique=False)
    if 'ix_sys_users_username' not in existing_indexes:
        op.create_index(op.f('ix_sys_users_username'), 'sys_users', ['username'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_userrole_menu')
    op.drop_table('sys_userinfo_roles')
    op.drop_index(op.f('ix_sys_users_username'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_phone'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_email'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_dept_id'), table_name='sys_users')
    op.drop_table('sys_users')
    op.drop_index(op.f('ix_sys_menus_parent_id'), table_name='sys_menus')
    op.drop_table('sys_menus')
    op.drop_table('sys_userloginlog')
    op.drop_table('sys_systemconfig')
    op.drop_index(op.f('ix_sys_roles_name'), table_name='sys_roles')
    op.drop_table('sys_roles')
    op.drop_table('sys_menumeta')
    op.drop_table('sys_logs')
    op.drop_index(op.f('ix_sys_ip_rules_ip_address'), table_name='sys_ip_rules')
    op.drop_table('sys_ip_rules')
    op.drop_table('sys_dictionary')
    op.drop_index(op.f('ix_sys_departments_parent_id'), table_name='sys_departments')
    op.drop_table('sys_departments')
    # ### end Alembic commands ###
